### PR TITLE
made blog poster middle

### PR DESCRIPTION
**Pull request by kalyan-vurugonda**
I have made a blog poster to the middle to look good.
If you like the changes, feel free to go for it or any feedback you can give me.

### CODE REVIEW

**Comment by priyankarpal** [comment]
Can you share a before & after Screenshot? @kalyan-vurugonda

**Comment by kalyan-vurugonda** [comment]
Before Screenshot : 
image

After Screenshot : 
image

**Comment by priyankarpal** [comment]
Yeah! that's cool.

**Review by priyankarpal — APPROVED** [review]

**Comment by poojasanwal** [comment]
Thanks for contributing @kalyan-vurugonda. Merged it!

**Pull request merged**
